CREATE TABLE DRAW_HISTORY (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    DrawDate DATE,
    Ball1 INTEGER,
    Ball2 INTEGER,
    Ball3 INTEGER,
    Ball4 INTEGER,
    Ball5 INTEGER,
    Ball6 INTEGER,
    BonusBall INTEGER,
    BallSet VARCHAR(20),
    Machine VARCHAR(20)
);

CREATE TABLE DRAW_FREQUENCY (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ball INTEGER,
    frequency INTEGER
);


CREATE TABLE PROPERTIES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    property VARCHAR(32),
    value VARCHAR(32)
);
