// Macro recorded on Sun May 24 2009 04:47:25 GMT+0100 (GMT)
komodo.assertMacroVersion(2);
if (komodo.view) { komodo.view.setFocus() };
komodo.doCommand('cmd_lineNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.doCommand('cmd_selectCharNext')
komodo.view.selection = ',';
